cleanup: don't add extra linefeed to end of error output

diff --git a/libexec/dockerize-boot b/libexec/dockerize-boot
--- a/libexec/dockerize-boot
+++ b/libexec/dockerize-boot
@@ -90,7 +90,7 @@ done
 set -- ${non_options}
 
 if [ -z "$1" ]; then
-  echo -e "error: you must specify an image name or git repository\n" 1>&2
+  echo "error: you must specify an image name or git repository" 1>&2
   exit 1
 fi
 
diff --git a/libexec/dockerize-git b/libexec/dockerize-git
--- a/libexec/dockerize-git
+++ b/libexec/dockerize-git
@@ -125,7 +125,7 @@ fi
 
 if [[ -z $($__exec "git show-ref --verify refs/remotes/origin/$git_repo_branch") ]]
 then
-  echo -e "error: branch $git_repo_branch does not exist\n" 1>&2
+  echo "error: branch $git_repo_branch does not exist" 1>&2
   exit 1
 else
   $__exec "git checkout -f origin/$git_repo_branch"
@@ -136,7 +136,7 @@ docker_image_tag="${git_repo_branch}.${commit_sha}"
 
 if [[ $PWD == $cloned_repository && ! -e Dockerfile ]]
 then
-  echo -e "error: this repository does not contain a Dockerfile, cannot build Docker image\n" 1>&2
+  echo "error: this repository does not contain a Dockerfile, cannot build Docker image" 1>&2
   exit 1
 fi
 
